### ISSUE TITLE
will not run locally

### ISSUE THREAD

**Issue by jcrugzz** [nodejitsu/browsenpm.org#11]
When i try to run this locally with the following command... 

``` sh
node index.js --config browsenpm.config.json
```

I get the following output:

`[object Object]`

and then it just dies.

**Comment by Swaagie** [comment]
Resolved with https://github.com/nodejitsu/browsenpm.org/commit/fe958d4751cb9848e61d0f9d191e46e8d85af3bd

also cradle is a bit silly for not exposing normal Error objects
