### ISSUE TITLE
adjust calculation of "slow" response time

### ISSUE THREAD

**Issue by jcrugzz** [nodejitsu/browsenpm.org#16]
When there is a narrower range of latency it is much easier to be interpreted as "slow" as the slowness is relative to itself.

**Comment by Swaagie** [comment]
:+1: to clarify what do you mean with narrower range?

**Comment by jcrugzz** [comment]
@Swaagie i have to read the code still but it seemed to be the case that if the response time varied less in terms of the range of its low and high, it was more common to be displayed as being "slow". But consider this conjecture until I read the code :tongue:

**Comment by Swaagie** [comment]
that would make sense as the standard deviation would be smaller as well, perhaps gotta do a normalization first and then use 2/3 times the stdev

**Comment by Swaagie** [comment]
simplified it by just using 1.5 times the previous moving average mean, the stdev actually says more about inner variation of the measurement than variance over time. See https://github.com/Moveo/npm-probe/commit/492043798d2ee808160655a2f526e8674c58400d
