### ISSUE TITLE
Minor rendering issues

### ISSUE THREAD

**Issue by indexzero** [nodejitsu/browsenpm.org#20]
Notice:
1. Alignment of the maintainers is borked
2. The "express" logo is on a white background so maybe we want to swap our colors? idk

![screen shot 2014-05-12 at 2 09 28 am](https://cloud.githubusercontent.com/assets/4624/2941194/455087aa-d99c-11e3-80dc-af7a246c6d95.png)

**Comment by 3rd-Eden** [comment]
Damn you long usernames :-)

**Comment by 3rd-Eden** [comment]
Usernames are fixed in nodejitsu/package-pagelet@master

**Comment by 3rd-Eden** [comment]
As for the express logo, they should just use a transparent PNG.
