### ISSUE TITLE
please add <title> to /package.json

### ISSUE THREAD

**Issue by tomByrer** [nodejitsu/browsenpm.org#27]
I was bookmarking your [awesome resource](http://browsenpm.org/package.json), but found I had to edit the bookmark/title.  I hope if gets a title so it would be more findable in search, etc.
I'd edit it myself, but don't understand the architecture.

**Comment by 3rd-Eden** [comment]
Thanks for your report! A better title will be included in the next release!

**Comment by tomByrer** [comment]
Cheers, & thanks for teaching me a bit more of your system with your PR.

**Comment by 3rd-Eden** [comment]
@tomByrer i'll be adding documentation about the page api on bigpipe.io soon, sorry for lacking docs :p
