### ISSUE TITLE
package.json "script" documentation is incorrect

### ISSUE THREAD

**Issue by bcronin** [nodejitsu/browsenpm.org#43]
The [package.json page](http://browsenpm.org/package.json) lists "**script**" (singular) as the string key for specifying a scripts object.  The key should be "**scripts**" (plural). https://www.npmjs.org/doc/misc/npm-scripts.html

**Comment by 3rd-Eden** [comment]
Thanks for reporting, i've fixed the issue and will deploy a version of browsenpm tomorrow.
