### ISSUE TITLE
Glyphs not loading

### ISSUE THREAD

**Issue by indexzero** [nodejitsu/browsenpm.org#6]
See below:

![screen shot 2014-04-26 at 11 40 38 pm](https://cloud.githubusercontent.com/assets/4624/2810430/cf8e4f96-cdbd-11e3-8603-089a68fb9726.png)

**Comment by Swaagie** [comment]
Similar to https://github.com/nodejitsu/browsenpm.org/issues/7

**Comment by Swaagie** [comment]
Added webfonts to static content, see https://github.com/nodejitsu/browsenpm.org/commit/f67cf4c2d8778756a1d4bf00d186fd67b6e5a24c
