### ISSUE TITLE
Header images should be in header

### ISSUE THREAD

**Issue by indexzero** [nodejitsu/browsenpm.org#7]
@Swaagie I've updated the header items by commenting out the ones we are not using yet, but we need the header images:

![screen shot 2014-04-26 at 11 52 00 pm](https://cloud.githubusercontent.com/assets/4624/2810448/5035ab8e-cdbf-11e3-9df8-e30a3b8afd07.png)

**Comment by Swaagie** [comment]
these images should be served via our versions cdn. As soon as we have browsenpm.org setup, we need to tell the cdn that it has a new resource and consequently it will fetch the source, see https://github.com/nodejitsu/nodejitsu-app/commit/5f59da73dfeb30b3fb528a0034936cfd5ad223f6. If you'd like to see how it looks locally (before our cdn caches it), change this line to `''` https://github.com/nodejitsu/contour/blob/master/assets/npm/defaults.styl#L17

**Comment by Swaagie** [comment]
Fixed for now by not depending on the CDN, can always do that later
