### ISSUE TITLE
configuring {page}/null?

### ISSUE THREAD

**Issue by indexzero** [nodejitsu/browsenpm.org#8]
Is this bad?

![screen shot 2014-04-26 at 11 54 51 pm](https://cloud.githubusercontent.com/assets/4624/2810452/bdb40886-cdbf-11e3-8df5-46cb624f2cf1.png)

**Comment by indexzero** [comment]
Relevant text reads:

```
bigpipe::primus initialised page for connection 1398570820761$5 +1ms
bigpipe:pagelet:navigation configuring navigation/null +10.9m
bigpipe:pagelet:status configuring status/null +11.6m
bigpipe:pagelet:search configuring search/null +11.6m
```

**Comment by Swaagie** [comment]
see first and last row of https://github.com/bigpipe/pagelet/blob/master/index.js#L30-L50, from what I can tell this is the default, doesn't hurt us at least

**Comment by 3rd-Eden** [comment]
Fixed in https://github.com/bigpipe/pagelet/commit/2ea64eee30a4c205c5b836e5a1af67187640b6d3
