### ISSUE TITLE
body still has margin:8px

### ISSUE THREAD

**Issue by indexzero** [nodejitsu/browsenpm.org#9]
This is the default from the user agent stylesheet, but I can see that in the `normalize.css` in contour [it is reset.](https://github.com/nodejitsu/contour/blob/master/assets/css/normalize.css#L69-L75)

@Swaagie Is there any reason why this wouldn't be loaded properly in `browsenpm`?

**Comment by Swaagie** [comment]
Fixed with https://github.com/nodejitsu/browsenpm.org/commit/fdb6349b7001f3b1d98a0718dc2a6566faca0674 and some additional fixes in bigpipe/pagelet CSS namespacing
